### ISSUE TITLE
Color singularity with RGB ImVec4 casting

### ISSUE THREAD

**Issue by Epholys** [eliasdaler/imgui-sfml#100]
Hello!

I've found a little issue about `ImVec4` <-> `sf::Color` conversion. It's not really a bug, but I think creating two new functions and/or adding a comment could be a good thing.

Using RGB colors as basis between `ImVec4` and `sf::Color` breaks the `ColorPicker` when selecting the black color (at the bottom of the color selection square for the `ImGuiColorEditFlags_PickerHueBar` picker). When doing this, the hue resets itself to the red color. It isn't a bug in dear imgui, as it's known and commented in [`imgui_demo.cpp#1253`](
https://github.com/ocornut/imgui/blob/f624455d7bb59ff5d2056c822e645073c323c6d8/imgui_demo.cpp#L1253).

So, I think it would be great to do something about it. Adding a comment explaining this behavior in `imconfig-SFML.h`, and adding two helper functions to do alternative conversions between `ImVec4`-encoded HSV color and `sf::Color`, using forward-declared `ColorConvertHSVtoRGB()` and `ColorConvertRGBtoHSV()` could do the trick.

If you think this is a good addition, I can do a pull request later this week.

And as always, thank you for this project!

**Comment by eliasdaler** [comment]
Hello. Can you please provide reproducing example?

I've tried this code and everything  works correctly for me:
```cpp
#include "imgui-SFML.h"
#include "imgui.h"

#include <SFML/Graphics/CircleShape.hpp>
#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>

int main() {
    sf::RenderWindow window(sf::VideoMode(640, 480), "ImGui + SFML = <3");
    window.setFramerateLimit(60);
    ImGui::SFML::Init(window);

    sf::CircleShape shape(100.f);
    ImVec4 color = ImVec4(1.0f,1.0f,1.0f,1.0f);

    shape.setFillColor(sf::Color::Green);

    sf::Clock deltaClock;
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if (event.type == sf::Event::Closed) {
                window.close();
            }
        }

        ImGui::SFML::Update(window, deltaClock.restart());

        ImGui::Begin("Hello, world!");
        ImGui::Text("Color picker:");
        ImGui::ColorPicker4("MyColor##4", (float*)&color, ImGuiColorEditFlags_PickerHueBar);
        ImGui::End();

        shape.setFillColor(color);

        window.clear();
        window.draw(shape);
        ImGui::SFML::Render(window);
        window.display();
    }

    ImGui::SFML::Shutdown();

    return 0;
}
```

**Comment by Epholys** [comment]
Oh, you're right, it's more complicated than I assumed.

The problem seems to be the round trip `sf::Color` -> `ImVec4` -> `sf::Color`. Some data will always be lost doing this way I think. So it's more of an edge case I didn't took care of in my project than a issue in imgui-sfml. I'll let you decide if this is the case before closing the Github issue.

For the record, here's the code to reproduce this behavior:

```c++
#include "imgui-SFML.h"
#include "imgui.h"

#include <SFML/Graphics/CircleShape.hpp>
#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>

int main() {
    sf::RenderWindow window(sf::VideoMode(640, 480), "ImGui + SFML = <3");
    window.setFramerateLimit(60);
    ImGui::SFML::Init(window);

    sf::CircleShape shape(100.f);
    sf::Color sf_color = sf::Color::Green;             // <--
    ImVec4 im_color = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);  // <--

    shape.setFillColor(sf_color);                      // <--

    sf::Clock deltaClock;
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if (event.type == sf::Event::Closed) {
                window.close();
            }
        }

        ImGui::SFML::Update(window, deltaClock.restart());

        ImGui::Begin("Hello, world!");
        ImGui::Text("Color picker:");
        
        im_color = shape.getFillColor();              // <--
        ImGui::ColorPicker4("MyColor##4", (float*)&im_color, ImGuiColorEditFlags_PickerHueBar);
        ImGui::End();

        sf_color = im_color;                         // <--
        shape.setFillColor(sf_color);                // <--

        window.clear();
        window.draw(shape);
        ImGui::SFML::Render(window);
        window.display();
    }

    ImGui::SFML::Shutdown();

    return 0;
}
```

**Comment by eliasdaler** [comment]
Yeah, that's mostly the problem of RGB/HSV being so different. SFML stores colors as RGB, so there's not much I can do about this. Implicitly converting `sf::Color` to `ImVec4` which stores color as HSV is not trivial and requires some calculations, so I'm not sure that I want to do that.
The solution seems to be: use HSV encoded `ImVec4` with ImGui and then cast it to `sf::Color` (RGB).

**Comment by Epholys** [comment]
Yes, that's what I've done, the colors are now encoded in `ImVec4` for the most part and only cast to `sf::Color` when there will not be any interaction with the user anymore.

Anyway, thank you for helping me with this and sorry for this false alarm. I'll close this issue.
