### ISSUE TITLE
How to add imgui to sf::Window?

### ISSUE THREAD

**Issue by ejamshidiasl** [eliasdaler/imgui-sfml#101]
Hello
i need to use opengl and opengl just work with Window not RenderWindow
is it possible to use imgui ????

**Comment by eliasdaler** [comment]
Yes, it's possible, though I've needed to add `Init` and `Render` overload to do so.
Please check out the latest commit. Does it work for you?

**Comment by eXpl0it3r** [comment]
But you *can* use OpenGL with `sf::RenderWindow` 😉

**Comment by eliasdaler** [comment]
Yeah, but just in case someone can't use `sf::RenderWindow` at all (e.g. some legacy code only sets up `sf::Window`), I've still made it all possible to do with only `sf::Window` being used. :)

**Comment by eliasdaler** [comment]
@ejamshidiasl - does the latest release workfor you?

**Comment by ejamshidiasl** [comment]
hi
i was involved in another work problem and didn't test it yet.(sorry)
i will test it tonight

**Comment by eliasdaler** [comment]
Is it still relevant?

**Comment by rul3rst4** [comment]
Maybe he is still testing haha
