### ISSUE TITLE
imgui-sfml undefined reference to imgui::image

### ISSUE THREAD

**Issue by GustavoPT** [eliasdaler/imgui-sfml#104]
I'm using latest sfml and latest imgui and latest imguisfml
i copied contents into the imconfig.h from imguisfml config and now getting this error when trying to build in codeblocks 

```
||=== Build: Debug in imguisfmltest (compiler: GNU GCC Compiler) ===|
C:\Users\gustx\Desktop\imguisfmltest\src\main.cpp|120|warning: 'playerUp' may be used uninitialized in this function [-Wmaybe-uninitialized]|
obj\Debug\D\cpp\imgui-master\imgui-sfml-master\imgui-SFML.o||In function `ZN5ImGui5ImageERKN2sf7TextureERKNS0_7Vector2IfEERKNS0_5ColorESA_':|
D:\cpp\imgui-master\imgui-sfml-master\imgui-SFML.cpp|561|undefined reference to `ImGui::Image(unsigned int, ImVec2 const&, ImVec2 const&, ImVec2 const&, ImVec4 const&, ImVec4 const&)'|
```

**Comment by eliasdaler** [comment]
Hello. Yeah, since some version, you also need to add 'imgui_widgets.cpp' to your build, otherwise the linker will fail.
I've added a note in README about it.

**Comment by GustavoPT** [comment]
ok that worked now i am getting 
`the procedure entry point _ZN2sf6Cursor14loadFromSystemENS0_4TypeE could not be located in the dynamic link library C:\Users\gustx\Desktop\imguisfmltest\bin\Debug\imguisfmltest.exe` i also already added opengl32 to the linker settings

**Comment by GustavoPT** [comment]
im using the starter code from this tutorial 
https://eliasdaler.github.io/using-imgui-with-sfml-pt1/

**Comment by eliasdaler** [comment]
Are you using SFML >= 2.5?

**Comment by eliasdaler** [comment]
Do basic SFML programs work in your CodeBlocks project?
I feel like they won't. This doesn't look like ImGui-SFML's problem, to be honest.
One more guess: you need to copy SFML's dlls to directory where .exe is.

**Comment by eliasdaler** [comment]
https://gist.github.com/eXpl0it3r/9fa3b0771f243f9e6cdcda7230523e3b
Can you please try this code in your project? It calls sf::Cursor::loadFromSystem, so if it works, then ImGui-SFML should work too.

**Comment by eliasdaler** [comment]
I think this is either SFML problem, or you're using incorrect binaries and should try to compile SFML yourself.
Either way, this doesn't look imgui-sfml's problem, so I'm closing this issue.
