### ISSUE TITLE
Is it support android?

### ISSUE THREAD

**Issue by ejamshidiasl** [eliasdaler/imgui-sfml#106]
Hello
i made android project and works fine. now i want to add imgui to it. but i got errors:
error: undefined reference to 'glEnable'
error: undefined reference to 'glDisable'
error: undefined reference to 'glOrthof'
and ....

is it support GLES?
how to solve problem?

**Comment by eliasdaler** [comment]
Yes, it does. You need to link to OpenGL.
Also check that `GL_VERSION_ES_CL_1_1` is defined.

**Comment by ejamshidiasl** [comment]
do  you know how to link opengl in Android.mk file?
and define `GL_VERSION_ES_CL_1_1` where?

**Comment by ejamshidiasl** [comment]
finally i did it!
now it works on android
thanks (link opengl)

**Comment by ejamshidiasl** [comment]
why flobalfontsize not working?
ImGuiIO io = ImGui::GetIO();
    io.FontGlobalScale = 1.5f;

**Comment by eliasdaler** [comment]
Because you're copying io, not getting reference to it. Should be:
```
ImGuiIO& io = ImGui::GetIO();
io.FontGlobalScale = 1.5f;
```

**Comment by ejamshidiasl** [comment]
YES
now it works
thank you bro
