### ISSUE TITLE
Event processed ?

### ISSUE THREAD

**Issue by scemino** [eliasdaler/imgui-sfml#107]
Is there a way to know if an event has been processed by ImGui or not ?
In my point and click game engine, I want to know if the mouse button has been pressed over a ImGui window or in the game.
Today when I click on a window, the current actor tries to walk to this position, but I dont want that.

**Comment by scemino** [comment]
Sorry duplicated question by #24

**Comment by eliasdaler** [comment]
No problem. :)
Will post here as well.

More info:

From ImGui:

> You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
       - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
       - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
       Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
