### ISSUE TITLE
Manual event handling

### ISSUE THREAD

**Issue by FelipeCarlin** [eliasdaler/imgui-sfml#114]
I have a rather big framework that cascades events through layers and overlays, right now imgui-sfml is handling everything that I put in front of it. I tried to do it manually by not calling `ProcessEvent()` and giving values to `io` (wich is a reference to `GetIO()`),  but nothing happens on a event. 

Am I missing something?

**Comment by eliasdaler** [comment]
Hello
I think the main culprit is `s_windowHasFocus` internal variable which gets set on Gained/LostFocus events. So maybe try to call `ImGui::SFML::ProcessEvent` at least for that kinds of events?

Also you need to be sure that you're processing events in a similar fashion as ImGui-SFML does. There's a lot of stuff that you need to set in `ImGuiIO` for it to function properly.

**Comment by FelipeCarlin** [comment]
Thanks
I tried another approach similar to the one 'ImGui-SFML' does, as you said, and worked almost perfectly. Now I just have to fix typing bugs.

**Comment by FelipeCarlin** [comment]
Now mouse events and window events work, but I cant get key events working, though `ctrl + c` and `ctrl + v` work perfectly

**Comment by eliasdaler** [comment]
I think if you just copy-paste relevant cases from that event switch, you'd get it to work :)

**Comment by eliasdaler** [comment]
Is some further explanations needed, or may I close the issue?

**Comment by FelipeCarlin** [comment]
I understand it now, thanks for the help
