### ISSUE TITLE
Re-upload current conan recipe to bincrafters

### ISSUE THREAD

**Issue by darcamo** [eliasdaler/imgui-sfml#115]
The conan recipe (`conanfile.py`) in this repository seems newer than the version currently installed in bincrafters (even though the version in bincrafters is also 2.1).

More specifically, the option in `imgui_revision` which is present in `conanfile.py` is not available when conan downloads from bincrafters, which indicates a previous version of the recipe was uploaded. Note that `conanfile.py` in this repository has this option for tag `v2.1`.

**Comment by eliasdaler** [comment]
PR is welcome. Sorry, I don't use Conan myself, so it's better if someone who does updates and tests it.

**Comment by darcamo** [comment]
I thought that the recipe here was the one originally uploaded to bincrafters (a community-driven repository for conan recipes). However, it seems that the recipe in bincrafters is instead from [this repository](https://github.com/bincrafters/conan-sfml).

It is not something that I can create a pull request for, since there is not code change to be made here. But I'll create an issue in bincrafters repository to maybe make use of the good things in the recipe in this repository (such as the possibility of choosing the imgui version instead of it being hard coded).

I'm closing the issue.
