### ISSUE TITLE
can not display image in another header file than main()

### ISSUE THREAD

**Issue by Thanh-Binh** [eliasdaler/imgui-sfml#116]
Hallo
In my framework, in the main program I call a visualization routine, which is implemented in another header file, I can plot all but can not visualize image, it is displayed as blank image.
main.cpp

```cpp
#include "visualize_header.hpp"
...
main ()
{
...
while (window.isOpen()) 
{ 
   .....
    visualize();
    window.clear(sf::Color(50, 50, 50));
    window.resetGLStates();
    ImGui::SFML::Render(window);
    window.display();
}
#########

#####visualize_header.hpp
visualize()
{
    ImGui::Begin("Application windows");
    sf::Texture imTexture;
    imTexture.loadFromFile("./test.bmp");
    ImGui::Image((void*)(intptr_t)imTexture.getNativeHandle(), ImVec2(imTexture.getSize().x,     imTexture.getSize().y));
    ImGui::End();
}
```

I do not know why? Can you please help? Thanks

**Comment by eliasdaler** [comment]
Hello. This is because your sf::Texture gets destroyed when visualize() function exists. You need to store this texture somewhere so it doesn't get destroyed before it can be drawn.

**Comment by Thanh-Binh** [comment]
thanks for your prompt response. 
I tried to input sf::Texture into visualize() by changing it like:
visualize(myTexture);
directly from main(). But it does not work.
Could you please explain me more details, How should I do it? Thanks

**Comment by eliasdaler** [comment]
Put these lines:

```sf::Texture imTexture;
imTexture.loadFromFile("./test.bmp");
```

before `while` loop in your `main` and then pass texture to `visualize` by reference

**Comment by eliasdaler** [comment]
Also please use ```ImGui::SFML::Image``` (see all the possible overloads in ```imgui-SFML.h```)

**Comment by Thanh-Binh** [comment]
look very good. Thanks

**Comment by eliasdaler** [comment]
You're welcome!
