### ISSUE TITLE
Using imgui in a thread?

### ISSUE THREAD

**Issue by Thanh-Binh** [eliasdaler/imgui-sfml#117]
Hi,
in main() I want to use a application + visualization thread, so that every time data is available, this thread is called for data processing and visualizing results. 
But it crashs by running with segmentation fault.

**Comment by Thanh-Binh** [comment]
in main()
......
        myData_t bioData(10, 3*sin(10*index));
        bioQueue.add(bioData);
        window.clear(sf::Color(50, 50, 50));
        window.resetGLStates();
        ImGui::SFML::Render(window);
.....

my thread looks like:

#include "thread_queue.h"
struct myData_t
{
	int64_t	timeStamp;
	int   	ecg;
	myData_t( int64_t ts, int _ecg) : timeStamp(ts), ecg(_ecg)
	{}
};

class testThread : public Thread
{
	wqueue<myData_t>& m_Queue;  
    sf::Texture imTextureH;
    bool isInitialized;
    int frame;
public:
	testThread(wqueue<myData_t>& queue) : m_Queue(queue)
	{
		isInitialized = false;
        frame = 0;
    };

    void* run()
	{
		while (1)
		{
			// thread waiting
			myData_t data = m_Queue.remove();

            // display in a new window
            std::cout << "B0" << std::endl;
            if (!isInitialized)
            {
                //ImGui::CreateContext();
                isInitialized = true;
            }
            ImGui::CreateContext();
            ImGui::Begin("Application windows");
            // simulated data            
            static float values[90] = { 0 };
            static int values_offset = 0;
            static float refresh_time = ImGui::GetTime(); // Create dummy data at fixed 60 hz rate for the demo
            for (; ImGui::GetTime() > refresh_time + 1.0f/60.0f; refresh_time += 1.0f/60.0f)
            {
                static float phase = 0.0f;
                values[values_offset] = cosf(phase);
                values_offset = (values_offset+1) % IM_ARRAYSIZE(values);
                phase += 0.10f*values_offset;
            }
            ImGui::PlotLines("Lines", values, IM_ARRAYSIZE(values), values_offset, "Animation", -1.0f, 1.0f, ImVec2(0,80));
            std::cout << "B3 at frame: " << frame++ << std::endl;
            ImGui::End();
        }
    }
};

**Comment by Thanh-Binh** [comment]
With this code, I have no error, but I can not see anything. No window named "Application windows" is displayed.
What is wrong here? Thanks for help.

**Comment by eliasdaler** [comment]
You're not syncing threads. Any ImGui function calls should happen between `ImGui::SFML::Update` and `ImGui::SFML::Render`. You should figure out how to sync two threads by either using standard library or other threading library you're using. This is not a problem with ImGui-SFML.

**Comment by Thanh-Binh** [comment]
OK. I have just found a bug by me. Thanks
