### ISSUE TITLE
Process classic SFML events  under IMGUI ?

### ISSUE THREAD

**Issue by binbinhfr** [eliasdaler/imgui-sfml#118]
Hi, thx for your nice work.

I just wonder if you have an example showing how you can still capture events that does not concern ImGUI and that concerns the classic SFML stuff "under" ImGUI (the rest of my application ;-) that relies on sf::Event::KeyReleased or sf::Keyboard::isKeyPressed).

Does IMGUI sends back some events telling if he got the focus during last frame ? So that I do not use mouse event or keyboard events for the rest of my application ?

I read about io.WantCaptureKeyboard and io.WantCaptureMouse but it is not very clear to me how and when I should use them. And they do not seem to give info about the fact that ImGUI has focus or not, but just if ImGUI has "consumed" some keyb or mouse events for himself.

**Comment by eliasdaler** [comment]
Hello.

Can you please tell me what you want to do exactly? It's not clear from your question. Why do you not want to use mouse/keyboard events from SFML?

**Comment by eliasdaler** [comment]
If you want to not process your normal input events when ImGui grabs it (e.g. when you're in a text box typing something), you need to check `ImGui::GetIO().WantCaptureKeyboard`/`Mouse`. And if it's true then you don't check your game/app input.

**Comment by binbinhfr** [comment]
I was infact also wondering how I can tell with those 2 flags that ImGui has the focus. But it seems that I missed IsWindowFocused() and IsWindowHovered(). Now I got it.

Thanks for your answer.
