### ISSUE TITLE
ImGuiConfigFlags_NoMouseCursorChange behaviour ?

### ISSUE THREAD

**Issue by binbinhfr** [eliasdaler/imgui-sfml#119]
hi @eliasdaler,

I am fighting with the mouse cursor in my app...
I choose ConfigWindowsResizeFromEdges = true to resize imgui windows by their borders.

When I don't set ImGuiConfigFlags_NoMouseCursorChange , your SFML backend uses the correct "resize" cursor on the edges of a ImGUI window, but the resize cursor is not shown anymore on the edges of the main window.

And if I set ImGuiConfigFlags_NoMouseCursorChange , it's the opposite : no more cursor change on Imgui borders, but ok on main window borders.

I cannot figure out how to enable both behaviours... Do you have an idea ?

**Comment by eliasdaler** [comment]
See #111 - unfortunately I didn't have time to look closer into this. It looks like a SFML bug for me and can't be easily fixed using ImGui-SFML's code only

**Comment by binbinhfr** [comment]
waooo... I wonder what I can tell to SFML people about it. I don't think they will go into ImGui and Imgui-SFML.... Thanks for your answer anyway.

**Comment by binbinhfr** [comment]
I see that the issue was already discussed with a russian guy in [https://github.com/eliasdaler/imgui-sfml/pull/110](url). But the discussion was in russian. Can you tell me if you found a solution ?

**Comment by eliasdaler** [comment]
There is no solution currently. The research is needed how SFML and SDL handle mouse cursors - the behaviour differs and my and the PR creator's previous research wasn't successful.

**Comment by binbinhfr** [comment]
So as far I understood, it works ok with SDL backend, but not with SMFL backend. So you think it's not a problem of IMGUI nor Imgui-SFML but a problem of SFML itself ?   I don't know how I can explain that to the SFML team...

**Comment by binbinhfr** [comment]
For those who needs, I just found a workaround. Switching the ImGuiConfigFlags_NoMouseCursorChange flag when ImGui really needs it. Here it is (it's a raw copy of my code, just to understand, but adapt to your own code)

[quote]
		static ImGuiIO& ioImgui = ImGui::GetIO();

		static bool imguiHasCursorPrev = true;
		bool imguiHasCursor = ioImgui.WantCaptureMouse || ioImgui.WantCaptureKeyboard;

		if (imguiHasCursor != imguiHasCursorPrev)
		{
			if (imguiHasCursor)
			{
				ioImgui.ConfigFlags &= !ImGuiConfigFlags_NoMouseCursorChange;
			}
			else
			{
				ioImgui.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;
				window.setMouseCursor(cursorDefault);
			}
			imguiHasCursorPrev = imguiHasCursor;
		}

[/quote]

note : "window" is my main sfml window.
and 	cursorDefault.loadFromSystem(sf::Cursor::Arrow);

Thx @eliasdaler for your answers, it helped me.

**Comment by Nightmare82** [comment]
Thanks a lot for the workaround @DaveInDev  this worked perfectly for me too!

**Comment by DEV-Sturm** [comment]
Great, 

one small correction - to preserve flags it should be:
`ioImgui.ConfigFlags &= ~ImGuiConfigFlags_NoMouseCursorChange;`
not
`ioImgui.ConfigFlags &= !ImGuiConfigFlags_NoMouseCursorChange;`
