### ISSUE TITLE
Getting rid of internal raw pointers to sf::Window and sf::RenderTarget

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#12]
Right now I'm keeping internal raw pointers to `sf::Window` and `sf::RenderTarget` which user passes. But it makes the whole binding a bit unsafe, because the user may delete or move them, and then the binding will just crash at next `Update` or `Render` call.

What I'm thinking is making users do this:

``` cpp
ImGui::SFML::Update(window, dt);
```

and this:

``` cpp
ImGui::SFML::Render(target); // this can be your window if it's sf::RenderWindow
```

So, you'll have to pass `sf::Window` and `sf::RenderTarget` on each call. This makes the design safer and better, because it will be impossible to break the binding. Internal pointers are used only in these functions, which means that it's possible to not store them.

**Comment by skyrpex** [comment]
in my opinion, this makes sense if swapping the window or render window doesn't break anything. 

anyway, if the documentation states that the passed window must be alive it should be enough...

**Comment by eliasdaler** [comment]
It won't break anything. You can change them at any time.

And yeah, documentation may be enough... but what this won't need any documentation at all. It will make an interface which is impossible to use incorrectly, which is a good thing.

**Comment by nidoro** [comment]
I approve.

**Comment by eliasdaler** [comment]
Done. Feel free to comment, if there's something you want to discuss about this change.
