### ISSUE TITLE
Need to ImageAnimButton with ImGui-SFML

### ISSUE THREAD

**Issue by mzadkol** [eliasdaler/imgui-sfml#120]
I m trying to load an image button as given in page [ImageAnimButton](https://github.com/ocornut/imgui/issues/1167) 

Will you please explain (as in your simple ImGui-SFML tutorial ) how we use it in our  SFML project. 

Anyway thanks for the IMGUI-SFML work

**Comment by eliasdaler** [comment]
Hello
Check out how ImGui::SFML::Image is implemented and pass texture ids from sf::Texture and calculate UV coordinates appropriately.

**Comment by mzadkol** [comment]
Hi
Thanks for the prompt reply.
I tried but unable make it work , will you please show me with an example 

(like this  )

**Comment by mzadkol** [comment]
Hi
Thanks for the prompt reply.
I tried but unable make it work , will you please show me with an example ( like this example of your ==>https://eliasdaler.github.io/using-imgui-with-sfml-pt1/

**Comment by mzadkol** [comment]
1) ok.. ..have seen the conversion of sfml texture to imgui textureid but now Getting an error => 'ImGuiWindow' was not declared in this scope <=

2) trying another button 'ImageButtonImpl ' also result in error => 'ImageButtonImpl' was not declared in this scope ; did you mean 'ImageButtonImg2' <=

3) I m just trying to have a button with image that changes on mouse over and on mouse click

Sorry if am annoying you.... am just new to all these stuff.

**Comment by eliasdaler** [comment]
You need to include <imgui_internal.h>

**Comment by mzadkol** [comment]
Hi 
where is the function convertGKTextureHandleToImTextureID()

**Comment by eliasdaler** [comment]
It's in imgui-SFML.cpp and you'll need to copy it to your code to use it

**Comment by mzadkol** [comment]
Thanks.
