### ISSUE TITLE
Include demo sources

### ISSUE THREAD

**Issue by pfirsich** [eliasdaler/imgui-sfml#121]
Hello,
It would be nice if there was a switch to include `IMGUI_DEMO_SOURCES` (i.e. `imgui_demo.cpp`) in the build (or to include it in the build). I am not very experienced with ImGui and find `ShowDemoWindow` very useful.

**Comment by eliasdaler** [comment]
Agreed. Will add `IMGUI_SFML_IMGUI_DEMO` option to CMake build

**Comment by eliasdaler** [comment]
Well, I was very busy, but thankfully @dubgron provided a PR, so now you can set `IMGUI_SFML_IMGUI_DEMO` to `ON` to build imgui_demo.cpp.
