### ISSUE TITLE
Imgui-sfml setup

### ISSUE THREAD

**Issue by Mechap** [eliasdaler/imgui-sfml#122]
So I'm using visual studio 19 
* I used this tutorial to setup imgui with sfml. https://eliasdaler.github.io/using-imgui-with-sfml-pt1/
* I also added all the content of imconfig-sfml.h to imconfig.h
When I ran the program, I got some issues 
![image](https://user-images.githubusercontent.com/54742369/83612572-dec4ea80-a582-11ea-90ad-4c0d25cc7814.png)
![image](https://user-images.githubusercontent.com/54742369/83612708-0fa51f80-a583-11ea-8e96-aa185fc65926.png)

**Comment by Mechap** [comment]
I also linked OpenGL because the tutorial recommend this if I get issues

**Comment by eliasdaler** [comment]
Are you sure you linked OpenGL? Because the linking errors exactly indicate that you probably didn't. 
You need to link to opengl32.lib

**Comment by Mechap** [comment]
Thank you. It works.

**Comment by eliasdaler** [comment]
You're welcome!
