### ISSUE TITLE
Looking for advice on updating and rendering at separate rates.

### ISSUE THREAD

**Issue by ka0s420** [eliasdaler/imgui-sfml#126]
Hi, up until just recently I was using a version of ImGui and ImGui_SFML from at least two years ago. I updated recently as I was getting back into my game engine project. 

Something must have changed along the way because it worked before, but now having my renderer run uncapped with my update being capped to 60fps causes issues with ImGui's NewFrame/EndFrame architecture.

Basically with the current update/render loop I cannot gurantee that the gui is updated only once per frame before ImGu::SFML::Render and it causes assert to called.

For now I have just had to push my render call into the same timestep as the update, but it's beyond irksome because it's a limited/unsophisticated approach. 

I figured I could perhaps create a frame manager and try and make sure the updates and renders are synced, however because I'm using this library I need to call the update which in turn calls newframe internally.

Is there any way to cicumvent this problem?

**Comment by eliasdaler** [comment]
Hello
I think it's not ImGui-SFML that change, but Dear ImGui did. My guess is that to achieve this you need to call `ImGui::Render();` on each update and then when you need to render, call `RenderDrawLists(ImGui::GetDrawData())` (the RenderDrawLists is not public, but maybe try to make function like this in imgui-SFML.cpp:

```cpp
void Render2() {
    RenderDrawLists(ImGui::GetDrawData());
}
```

and if it works, maybe it should get included in imgui-sfml in some form. :)

**Comment by ka0s420** [comment]
@eliasdaler Hi thanks for responding :) 

I tried :

`void RenderAccumulatedFrames(sf::RenderTarget& target) {
    target.resetGLStates();
    RenderDrawLists(ImGui::GetDrawData());
}
void RenderAccumulatedFrames() {
    RenderDrawLists(ImGui::GetDrawData());
}`

But it always seems to result in: 

`Exception thrown: read access violation.
**draw_data** was nullptr.`

**Comment by ka0s420** [comment]
It's really not pretty, but to get it to work I had to cache the DrawData in a static variable and check to see i f the call to ImGui::GetDrawData returned nullptr or not.

```c++
static ImDrawData cachedDrawData;
void RenderAccumulatedFrames(sf::RenderTarget& target) {
    target.resetGLStates();
    if(ImGui::GetDrawData())
        cachedDrawData = *ImGui::GetDrawData();

    RenderDrawLists(&cachedDrawData);
}
void RenderAccumulatedFrames() {
    if(ImGui::GetDrawData())
        cachedDrawData = *ImGui::GetDrawData();
    RenderDrawLists(&cachedDrawData);
}

```
Still open to any other suggestions, if you have any 👍

**Comment by eliasdaler** [comment]
It looks like you're not calling `ImGui::Render` in the same frame as you do `ImGui::GetDrawData()` (or there is some `ImGui::NewFrame` or something like that between these calls). It really depends on how your main loop is written.

**Comment by ka0s420** [comment]
It sounds like what you're saying is how I described my situation originally, as I was saying the update and render don't necessarily happen in a linear fashion. My main loop is this: 

```c++
void Engine::run()
	{
		

		sf::Clock clock;
		sf::Time timeSinceLastUpdate = sf::Time::Zero;
		//ImGui::NewFrame();
		
		while (mWindow.isOpen())
		{
			sf::Time elapsedTime = clock.restart();
			timeSinceLastUpdate += elapsedTime;
			while (timeSinceLastUpdate > mTimePerFrame)
			{
				timeSinceLastUpdate -= mTimePerFrame;
				processEvents();
				update(mTimePerFrame);
			}
			render();
			updateStatistics(elapsedTime);
		}
		
	}

```

It's a fixed 30fps timestep for the update and event processes, and an uncapped render rate. It's pretty much the main loop from one of the few sfml game books that came out of pakt publishing I believe. 

the update is this: 

```c++
ImGui::ShowDemoWindow(&p_open);
	for (auto& g : guis)
		g->update();
	ImGui::SFML::Render();
``` 
and simply ```ImGui::SFML::RenderAccumulatedFrames();``` in the render function.


"It looks like you're not calling ImGui::Render in the same frame as you do ImGui::GetDrawData()"

Yes I am. In update I call ImGui::Render and in the render I do ImGui::SFML::RenderAccuulatedFrames() (the function I added. 

Are you saying I should be calling ImGui::SFML::update in update and ImGui::Render when rendering (when there hasn't been an update call) and RenderAccumulatedFrames in render when there has been an update? If that's the case then I will have to do the sort of branching check like i did already regardless.

I'm surprised because I thought my main loop was a common way of doing this :|

**Comment by ka0s420** [comment]
I don't know if it will be of any help, as it seems like maybe it's impossile to do what I want (any differently than the hack I implemented before) But I figured a minimal example could be useful 🤷 

```c++
#include <SFML/Graphics.hpp>
#include "ImGui.h"
#include "ImGui-SFML.h"


void update(sf::Time dt, sf::RenderWindow& window);
void processEvents(sf::RenderWindow& window);
void render(sf::RenderWindow& window);

int main()
{
	sf::RenderWindow window;
	window.create(sf::VideoMode(800, 600), "window");
	ImGui::SFML::Init(window);


	sf::Clock clock;
	sf::Time timeSinceLastUpdate = sf::Time::Zero;
	sf::Time mTimePerFrame = sf::seconds(1.f / 60.f);

	while (window.isOpen())
	{
		sf::Time elapsedTime = clock.restart();
		timeSinceLastUpdate += elapsedTime;
		while (timeSinceLastUpdate > mTimePerFrame)
		{
			timeSinceLastUpdate -= mTimePerFrame;
			processEvents(window);
			update(mTimePerFrame, window);
		}
		render(window);
	}
	return 0;
}

void update(sf::Time dt, sf::RenderWindow& window)
{
	ImGui::SFML::Update(window, dt);
	ImGui::Begin("Hello!", NULL);
	ImGui::Button("click me", ImVec2());
	ImGui::End();
}

void processEvents(sf::RenderWindow& window)
{
	sf::Event event;
	while (window.pollEvent(event))
	{
		ImGui::SFML::ProcessEvent(event);
	}
}

void render(sf::RenderWindow& window)
{
	ImGui::SFML::Render();
}
```

The above minimal example was how my code was originally before using ImGui::Render and implementing things in the ImGui-SFML header/cpp.

**Comment by eliasdaler** [comment]
Closing this for now - not sure that there's anything I can change in ImGui-SFML's code to make this easier.

**Comment by cheofusi** [comment]
Hi, 

Same problem here. Happens when I draw the ImGui widgets more frequently than I render. I'm using the same minimal example above. Tried adding `ImGui::EndFrame()` to the end of the update function like the README says but still no success.

Any advice?

**Comment by Gaylubeoil** [comment]
Hey, was any solution to this found ?

**Comment by K20shores** [comment]
This [stackoverflow answer](https://stackoverflow.com/questions/77507026/forgot-to-call-imguinewframe) is about the same thing and it's solution worked for me
