### ISSUE TITLE
CMake + SFML + imgui   By not providing "FindImGui-SFML.cmake"

### ISSUE THREAD

**Issue by Hitoku** [eliasdaler/imgui-sfml#130]
Hello, I have a CMakeList like this.

```
cmake_minimum_required(VERSION 3.17)
project(test VERSION 0.1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)

# SFML
## If you want to link SFML statically
set(CMAKE_EXE_LINKER_FLAGS "-static -static-libgcc")
set(SFML_STATIC_LIBRARIES TRUE)

## In most cases better set in the CMake cache
set(SFML_DIR "./library/frameworks/SFML-2.5.1/lib/cmake/SFML")
set(ImGui_DIR "./library/frameworks/imgui")
set(ImGui-SFML_DIR "./library/frameworks/imgui-sfml/cmake")

add_executable(test src/main.cpp)

find_package(SFML 2.5 COMPONENTS system window graphics network audio REQUIRED)
target_link_libraries(test sfml-system sfml-window sfml-graphics sfml-network sfml-audio)
target_include_directories(test PUBLIC ${SFML_INCLUDE_DIRS})

find_package(ImGui-SFML REQUIRED)
target_link_libraries(test PRIVATE ImGui-SFML::ImGui-SFML)
target_include_directories(test PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/library/frameworks/imgui)
target_include_directories(test PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/library/frameworks/imgui-sfml)
```
When I compile, I get this message.

```
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "FindImGui-SFML.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ImGui-SFML", but CMake did not find one.

  Could not find a package configuration file provided by "ImGui-SFML" with
  any of the following names:

    ImGui-SFMLConfig.cmake
    imgui-sfml-config.cmake

  Add the installation prefix of "ImGui-SFML" to CMAKE_PREFIX_PATH or set
  "ImGui-SFML_DIR" to a directory containing one of the above files.  If
  "ImGui-SFML" provides a separate development package or SDK, be sure it has
  been installed.
```
![image](https://user-images.githubusercontent.com/41386274/90635556-fb8fc680-e231-11ea-8f19-190826b9b6dd.png)

I can't figure out where I get the FindImGui-SFML.cmake file from.

**Comment by DmitruMoth** [comment]
You can compile and install lib before use it
`make install`
Also you can use add_subdirectory(pathToRootImgui-SFML) in your CMakeLists.txt
The same with SFML

**Comment by Hitoku** [comment]
> You can compile and install lib before use it
> `make install`
> Also you can use add_subdirectory(pathToRootImgui-SFML) in your CMakeLists.txt
> The same with SFML

I'm trying to put it together like this.
```
cmake C:\\Users\\admin3\\CLionProjects\\test\\library\\frameworks\\imgui-sfml -DIMGUI_DIR=C:\\Users\\admin3\\CLionProjects\\test\\library\\frameworks\\imgui -DSFML_DIR=C:\\Users\\admin3\\CLionProjects\\test\\library\\frameworks\\SFML-2.5.1 -D"CMAKE_MAKE_PROGRAM:PATH=‪C:\\msys64\\usr\\bin\\cmake.exe" -D"CMAKE_CXX_COMPILER:PATH=C:\\msys64\\mingw32\\bin\\g++.exe" -G "Unix Makefiles"
```
![image](https://user-images.githubusercontent.com/41386274/90732830-5548cd00-e2d4-11ea-85a0-e7f8fd296802.png)
In PATH everything is spelled out and the compiler can be seen

**Comment by DmitruMoth** [comment]
Is your cmake installed via mingw(or msys2) or manually?

**Comment by DmitruMoth** [comment]
If cmake installed via pacman in mingw/msys (packet: mingw-w64-x86_64-cmake) try to do this:
1. Copy all folders from root SFML and ImGui(bin, include etc...) to minw32 or mingw64 folder
2. In CMakeLists.txt just write find_package, without set sfml_dir
3. In Clion settings(Build - Toolchains) pick custom cmake executable and set path to cmake, by default - bundled cmake 
4. Reload cmake project

**Comment by Hitoku** [comment]
> Is your cmake installed via mingw(or msys2) or manually?
The last thing I could do
Yes, I use Msys2 and mingw-w64-x86_64-toolchain + mingw-w64-x86_64-cmake.

I get this error, but there is a file there
```
CMake Error at CMakeLists.txt:47 (message):
  SFML 2 directory not found.  Set SFML_DIR to directory where SFML was built
  (or one which ccontains SFMLConfig.cmake)
```
![image](https://user-images.githubusercontent.com/41386274/90805760-c0ba8b00-e324-11ea-88af-05993bf58e32.png)
![image](https://user-images.githubusercontent.com/41386274/90806026-227af500-e325-11ea-89f8-2a3cf23392db.png)

**Comment by DmitruMoth** [comment]
Use `cmake -G "MinGW Makefiles"`
Also you need mingw build of SFML

**Comment by eliasdaler** [comment]
Closing for now - the provided answer should work.
