### ISSUE TITLE
Is there a way to increment slider integers on even numbers only or odd?

### ISSUE THREAD

**Issue by patrikpatrik** [eliasdaler/imgui-sfml#138]
Sorry if this has been answered before. But I'm using:
```cpp
ImGui::SliderInt("sizeInt", &ROWCOL, 0, 200);
```

Is there a way to increment by every even number instead of ++ ? Thanks in advance!

**Comment by eliasdaler** [comment]
Hello. 
I tried to find overload which will allow you to go in steps, but I couldn't. Found this: https://github.com/ocornut/imgui/issues/1815 (and it looks like it's on TODO list, but not a priority)

I think you can try something like this:
```cpp
if (ImGui::SliderInt("sizeInt", &ROWCOL, 0, 200)) { // if value has changed
    ROWCOL = (ROWCOL / 2) * 2; // round to even number
}

**Comment by patrikpatrik** [comment]
@eliasdaler Hi,
Thank you for the quick response. I've tried the snippit above but it still seems to increment by one. I tried asking coconut but he closed it for some reason. I keep thinking there is a way, I just cant seem to figure it out. In the meantime I've decided to just use mouseButton events to increment up or down by 2 for the ROWCOL size.

**Comment by eliasdaler** [comment]
Your issue was closed, because you didn't follow the issue template.

I don't think that using events is a right way to do this, you should probably try to use the method I've suggested. If it still doesn't work, try asking it in ImGui's Discord - it' not ImGui-SFML's issue at this point. Closing.
