### ISSUE TITLE
How to check if sf::Event was used?

### ISSUE THREAD

**Issue by sasichkamega** [eliasdaler/imgui-sfml#140]
How to check if sf::Event was used in a ImGui::SFML::ProcessEvent() function or not? To filter out events that should not be used by engine.

**Comment by eliasdaler** [comment]
Hello
I think what you need is [this](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-to-my-application)
