### ISSUE TITLE
warning C4244: 'argument': conversion from 'const T' to 'float', possible loss of data, with [ T=int ]

### ISSUE THREAD

**Issue by andrew-gresyk** [eliasdaler/imgui-sfml#142]
The warning is reported on MS VS Community 16.8.2 in
https://github.com/eliasdaler/imgui-sfml/blob/5ab660a13bc997225587eea88755f22f999f7ba9/imgui-SFML.cpp#L401

Compiled with /W4 and /WX (https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-160)

**Comment by eliasdaler** [comment]
Fixed by #143
