### ISSUE TITLE
Cursor changes to resize when ImGui is not rendered

### ISSUE THREAD

**Issue by EdmondScorp** [eliasdaler/imgui-sfml#149]
Hi guys, I am new to ImGui so this might not be a an actual bug.
Basically, even when ImGui is not rendered and I hover my mouse over the edges (which I cant see, just by remembering the spot), my cursor changes to "Resize" and I can actually resize, because when I render back ImGui its sizes are changed.
How do I prevent this "invisible" resizing?

**Comment by eliasdaler** [comment]
Hello
Sorry, I can't understand what's happening. Can you provide screenshots/GIF/video which shows the buggy behaviour?

**Comment by EdmondScorp** [comment]
Desktop 2021.01.26 - 20.46.38.01.mp4
<https://drive.google.com/file/d/1xI8wd3yxPKmFkiYb8O0q3TRTy3_IMPIc/view?usp=drive_web>

As you can see, even when I am not rendering, the cursor still changes to
"Resize" mode and I can resize it without even seeing.

**Comment by eliasdaler** [comment]
The video doesn't have public access - please set it to "everyone with the link can view"

**Comment by EdmondScorp** [comment]
Sorry, I think you should be able to access it now.

**Comment by eliasdaler** [comment]
I see
Well, if you don't want to see any side-effects of ImGui, you need to **not** call any ImGui function (`ProcessEvent`, `Update`, `Render`). Mouse cursor is changed inside `Update` no matter if `Render` is called or not.

**Comment by eliasdaler** [comment]
Is this still not solved?

**Comment by EdmondScorp** [comment]
well I just don't create any window whenever I don't need to, but I still
call ProcessEvent, Update, Render and it works :P

**Comment by eliasdaler** [comment]
Okay, I'm closing this, as I think that I've answered your question - to "hide" ImGui, you need to not only stop rendering it, but also stop sending any events to it and calling Update.
