### ISSUE TITLE
If you only draw ImGui stuff, it's not displayed if you don't call resetGLStates first

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#15]
`resetGLStates`  is automatically called by SFML on the first `target.draw` call. It ensures that OpenGL state is set up correctly.

But I have no idea if calling `resetGLStates` on the first `RenderDrawLists` call is safe and won't mess everything up if you draw other stuff along with ImGui. If someone has ideas how to fix it correctly, please help. :D

**Comment by iamPHEN** [comment]
Should be fine to call resetGLStates. I took a peek at resetGLStates, and it just calls a bunch opengl calls to set the state appropriately.

https://github.com/SFML/SFML/blob/2df9abf34172f168c3d9b763553d485bc29c9eef/src/SFML/Graphics/RenderTarget.cpp#L356

That being said, RenderDrawList is likely not setting something correctly. Adding this to `RenderDrawLists` seems to fix it:

```
glDisable(GL_LIGHTING);
glEnableClientState(GL_VERTEX_ARRAY);
glEnableClientState(GL_COLOR_ARRAY);
glEnableClientState(GL_TEXTURE_COORD_ARRAY);

**Comment by xelfe** [comment]
So guys how to fix it ? It's look that I get same issue. If I remove  
`
....
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);
....
window.draw(shape);
`
from the main.cpp , I cannot see Imgui stuff.

**Comment by eliasdaler** [comment]
Okay, I'll take a closer look at it this weekend. For some reason it broke some of my code, but maybe it was my fault.

**Comment by eliasdaler** [comment]
[Now calling this thing internally!](https://github.com/eliasdaler/imgui-sfml/commit/8c60004fbffa995b1c44c2608cf9b43d18f4f7ca)
