### ISSUE TITLE
Can't Complie the [imgui_sfml_example]

### ISSUE THREAD

**Issue by Smalldy** [eliasdaler/imgui-sfml#153]
win10 
sfml ver = 2.5.1
imgui ver = 1.82 WIP
imgui-sfml ver = lasted
ide = vs2017
cmake ver = 3.15.5

I successfully compiled two libraries： sfml and imgui-sfml., but CAN NOT to complie the project [imgui_sfml_example] .

I got some link error like: unresolved external symbol "bool __cdecl ImGui::BeginTable(char const *,int,int,struct ImVec2 const &,float)" (?BeginTable@ImGui@@YA_NPBDHHABUImVec2@@M@Z....

How can I fix it ?

**Comment by eliasdaler** [comment]
Hello
You need to add imgui_tables.cpp (from ImGui) to your build.

**Comment by Smalldy** [comment]
thks and it works in the project **created by my self**! 
But it is very puzzing to me.
In fact, I want to fllow  --> "Building and integrating into your CMake project"  in readme document to build a shared lib, After I set IMGUI_SFML_BUILD_EXAMPLES = NO, the link error occured ..

should I need to add imgui_tables.cpp to **imgui-sfml projcet** to build the example?
thanks for your help.

**Comment by eliasdaler** [comment]
Strange. Maybe FindImGui.cmake wasn't behaving right. Try to checkout to this commit: https://github.com/eliasdaler/imgui-sfml/commit/4b3ce009be611570d76480895f492c9734bf62ff
I think it should work with CMake project well.

**Comment by Smalldy** [comment]
thanks , it works.
Now I can use the shared lib without imgui_tables.cpp.

(IMGUI_SFML_BUILD_EXAMPLES = NO  need imgui_demo.cpp , Maybe it's better to add some relevant judgment?)
