### ISSUE TITLE
Font loading

### ISSUE THREAD

**Issue by EdmondScorp** [eliasdaler/imgui-sfml#154]
I am trying to load fonts and some of them don't work. The paths are all correct, but for some reason some don't work. I get this error
"C:\Windows\Fonts\BSSYM7.TTF" (failed to set the Unicode character set)
Assertion failed: g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8() ?"

**Comment by eliasdaler** [comment]
Hello
Just to be sure: do some custom fonts work? Or is it just ones that have Unicode symbols in them?

**Comment by EdmondScorp** [comment]
I don't know much from fonts but for example, Verdana, Arial, Calibri,
Impact and many others work but say Bookshelf Symbol 7 or MS Sans Serif
don't work.

**Comment by eliasdaler** [comment]
I see. This doesn't look like ImGui-SFML issue, more like ImGui issue. Please reads ImGui's docs to see how to get Unicode fonts to work. Searching for GetTexDataAsRGBA32 might give you some ideas.

**Comment by eliasdaler** [comment]
Also, are you sure that you call `ImGui::SFML::UpdateFontTexture` as described in README?

**Comment by EdmondScorp** [comment]
Yes, I do. I will read ImGui's docs more thoroughly :)

**Comment by eliasdaler** [comment]
After some investigation, I've found this when loading "Bookshelf Symbol 7" :
![image](https://user-images.githubusercontent.com/1285136/109402365-6733b880-7966-11eb-9f62-124d83323e3e.png)

Basically, stb/truetype which ImGui uses for font loading fails to open the font. 
Here's a similar issue: https://github.com/nothings/stb/issues/1086

So, it's definitely stb/truetype issue, not ImGui-SFML issue. So my suggestions would be to either use a font that maps to Unicode properly or try to use `sf::Font`, see if it manages to open it, render text to `sf::RenderTexture` and then display it with `ImGui::Image`/`ImGui::ImageButton`.

**Comment by EdmondScorp** [comment]
No, sf::Font won't load either. Thanks for your investigations :)

**Comment by eliasdaler** [comment]
No problem. :)
