### ISSUE TITLE
Add BUILD_SHARED_LIBS cmake option to CmakeList.txt

### ISSUE THREAD

**Issue by Smalldy** [eliasdaler/imgui-sfml#155]
Hi, Guys! I'm back~
It seems you forget to add the `BUILD_SHARED_LIBS` to cmake option in your CMakeList.txt
It takes my long time to found this (I'm newer).

**Comment by eliasdaler** [comment]
Hello.
There's no need to that. Passing it via `-DBUILD_SHARED_LIBS=<ON/OFF>` works.
