### ISSUE TITLE
Drawing ImGui on sf::RenderTexture?

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#16]
It seems like drawing ImGui on renderTexture should be done like this:
```cpp
window.clear();
renderTexture.clear();
renderTexture.setActive();
ImGui::Render();
renderTexture.display();
sf::Sprite sprite(renderTexture.getTexture());
window.setActive();
window.draw(sprite);
window.display();
```

Unfortunately, this doesn't work. This is probably some small bug in `RenderDrawLists` function. I don't want to work on this atm, but if someone manages to fix it - feel free to do a PR.

**Comment by iamPHEN** [comment]
Might have to call window.resetGLStates();  before any window.draw(..);  

http://www.sfml-dev.org/tutorials/2.0/window-opengl.php#using-opengl-together-with-the-graphics-module

https://github.com/SFML/SFML/blob/2df9abf34172f168c3d9b763553d485bc29c9eef/src/SFML/Graphics/RenderTarget.cpp#L356

**Comment by MarkSill** [comment]
To clarify on this, you actually need to use `resetGLStates()` just before you call `ImGui::Render()`, or at least that's how I fixed this in my own code.

**Comment by eliasdaler** [comment]
@MarkSill, do you render stuff on RenderTexture? It seems like `resetGLStates()` is a fix to #20. But I don't want to call it, it does too much stuff and causes huge overhead compared to other functions.

**Comment by MarkSill** [comment]
I'm rendering onto a texture, and calling `resetGLStates()` was the way I got it to work. I'm not working with intensive rendering, so the speed of the call isn't a big issue for me.

I just realized I didn't mention this above: I'm calling `resetGLStates()` on the texture, not the window. Based on (very) minor testing, this is a little faster than calling it on the window (~3 microseconds on my laptop with integrated graphics). Calling `resetGLStates()` on the texture on my laptop takes about ~10 microseconds, according to `sf::Clock`. It doesn't seem to be quite as long a call as it's made out to be.

Last thing: This appears to only be necessary if **only** drawing ImGui. If I draw any other SFML objects onto the texture before drawing ImGui, the call to `resetGLStates()` is not needed.

**Comment by eliasdaler** [comment]
Oh, okay, thanks! I'll take a look at it soon, but I'll probably add something like

```cpp
ImGui::SFML::Render(sf::RenderTarget& target)
{
     target.resetGlStates();
     ImGui::Render();
}
```

**Comment by JayhawkZombie** [comment]
I don't know if anyone else is presented with a similar problem, but using `sf::RenderTexture` with ImGui results in a flipped texture.  Drawing the same texture outside of ImGUI works fine, but it renders flipped when trying to render an ImGui::Image.  The same goes for ImageButton.

I am calling .display for each texture after trying to draw it, and I've tried with both using `resetGLStates()` and not calling `resetGLStates()` with the same results both times.  If it makes any difference, I'm using SFML 2.4.1 and your most recent commit to this repo.

**Comment by eliasdaler** [comment]
Can you please provide a minimal source code which has the problem? I'll check out what goes wrong.

**Comment by eliasdaler** [comment]
It only took me three months. xD
[Commit](https://github.com/eliasdaler/imgui-sfml/commit/8c60004fbffa995b1c44c2608cf9b43d18f4f7ca)
