### ISSUE TITLE
What  'GetCursorPos'  does?

### ISSUE THREAD

**Issue by EfeOsman** [eliasdaler/imgui-sfml#160]
I was trying to get position of rendertexture when rendering into tabbar with ImGui::Image 
then i tried GetCursorPos and it did work but i dont know why(:rofl: ) 
so im wondering what 'GetCursorPos' really does?
(sorry for opening 2 issue for today but imgui or imgui-sfml doesnt have discord or something :(...)

**Comment by eliasdaler** [comment]
Please read [this](https://github.com/ocornut/imgui/blob/master/imgui.h#L401)
`GetCursorPos` returns a position of where the next widget will be placed. So, to get the position of your RenderTexture, you need to call `GetCursorPos` before calling `ImGui::Image`

For future questions about Dear ImGui, please consider using [Dear ImGui's discussions](https://github.com/ocornut/imgui/discussions) instead.
