### ISSUE TITLE
Runtime error when pressing keys like "print screen"

### ISSUE THREAD

**Issue by angeluriot** [eliasdaler/imgui-sfml#168]
In [**imgui-SFML.cpp**](https://github.com/eliasdaler/imgui-sfml/blob/master/imgui-SFML.cpp), if `event.key.code` is `-1`, there is an error on line **307**. For example by pressing the `print screen` key.

**Comment by eliasdaler** [comment]
Yeah, I see the issue. Will fix this during this weekend :)

**Comment by eliasdaler** [comment]
Fixed, sorry for the delay.
