### ISSUE TITLE
Mouse cursor position on startup is (0, 0) until moved

### ISSUE THREAD

**Issue by ShavitGH** [eliasdaler/imgui-sfml#170]
The mouse isn't moved on startup, the position remains 0, 0.
(Has consequences if you have an interactive object on that spot, before the mouse is moved)

Can be fixed by adding the following in imgui-SFML.cpp::Init()
`s_touchPos = sf::Mouse::getPosition(window);`

**Comment by eliasdaler** [comment]
Hello

Please check out this branch and see if it fixes the problem:

https://github.com/eliasdaler/imgui-sfml/tree/fix-init-mouse-pos

**Comment by eliasdaler** [comment]
Closing as outdated. Feel free to re-open if someone stumbles upon this one again.
