### ISSUE TITLE
Instructions for Manual Integration on blog post and README seem to be outdated

### ISSUE THREAD

**Issue by nathan-abraham** [eliasdaler/imgui-sfml#173]
Disclaimer: This is my very first github issue, so please don't be too harsh on me. Also, I'm a newbie when it comes to C++ libraries and stuff.

When trying to integrate imgui-sfml manually, I followed all the instructions on the blog post and README, but I still got linking errors. They both said to link opengl, which was kind of vague (especially for a newbie like me). It took me some time to realize it was talking about the opengl32 library file, so I think you should specify that on the blog post and README. Even after linking this file, I still got linking errors. After searching the internet for a very long time, I realized that in addition to adding these files,
- **imgui.cpp**
- **imgui_draw.cpp**
- **imgui_widgets.cpp**
- **imgui-SFML.cpp**
- **imgui_demo.cpp** 

you also need to add *imgui_tables.cpp*. After adding *imgui_tables.cpp*, all my linking errors went away. This isn't just a problem for me; an SFML forum thread detailing this same issue can be found [here](https://en.sfml-dev.org/forums/index.php?topic=27838.0). I think you should update your blog/README to say that add imgui_tables.cpp if you still get linking errors even after linking opengl32.

**Comment by eliasdaler** [comment]
It's in README:

> Add imgui.cpp, imgui_widgets.cpp, imgui_draw.cpp and imgui_tables.cpp to your build/project

But yeah, the blog post is outdated, I'll update it.

**Comment by nathan-abraham** [comment]
Ok, thanks for your fast response!
