### ISSUE TITLE
Having trouble plotting high-density ImPlot widgets

### ISSUE THREAD

**Issue by cheofusi** [eliasdaler/imgui-sfml#175]
Hi.

I've been able to get Implot working together with imgui-sfml and just learned that ImGui uses 16-bit indexing by default which isn't enough for large meshes.

I've tried the first fix i.e  uncommenting  `#define ImDrawIdx unsigned int` in the ImGui `imconfig.h file` but with no success, as the ImGui window becomes seriously distorted.

Was wondering if imgui-sfml implements the second fix described in this [issue](https://github.com/ocornut/imgui/issues/2591)

Great work mates

**Comment by eliasdaler** [comment]
Hello
#178 should do it. Might do a release after it gets merged.

**Comment by eliasdaler** [comment]
It's now merged. Please check the master branch and if #178 solves the problem for you.

**Comment by cheofusi** [comment]
Yup, problem solved. Thanks mates
