### ISSUE TITLE
SFML View to ImGui Image

### ISSUE THREAD

**Issue by dgrfps** [eliasdaler/imgui-sfml#195]
I'm using docking and trying to make a viewport window.
The problem is that i can't convert the SFML view port to imgui-SFML desired RenderTexture.

```cpp
Actually sf::RenderTexture().getTexture() doesn't display the sfml window view.
```
Could you please help me?

```cpp
ImGui::SetNextWindowSize({ 500, 500 }, ImGuiCond_FirstUseEver);
ImGui::Begin("Cam");

	ImGui::Image(sf::RenderTexture().getTexture(), ImGui::GetWindowSize(), sf::Color::White, sf::Color::Red);

ImGui::End();
```

**Comment by eliasdaler** [comment]
Hello

You can't create a temporary RenderTexture like that. You should create a proper sf::RenderTexture and then render stuff to it. Afterwards, you use `ImGui::Image(const sf::RenderTexture& texture);` overload to draw it with ImGui.
