### ISSUE TITLE
Modal dialog visual glitch as of ImGui v1.86

### ISSUE THREAD

**Issue by sam20908** [eliasdaler/imgui-sfml#198]
![image](https://user-images.githubusercontent.com/18388795/159169868-e49e11f7-aeeb-463f-8b2c-41423264c0dd.png)

It wasn't like this until recently, so I assume the issue lies within this backend. See the comment from imgui's author about this issue: https://github.com/ocornut/imgui/issues/4863#issuecomment-1005229794

**Comment by eliasdaler** [comment]
Hello
Can you please check out this branch and see if it works for you? https://github.com/eliasdaler/imgui-sfml/tree/idxoffset_fix

**Comment by eliasdaler** [comment]
Good, merged into master. Thanks for reporting.
