### ISSUE TITLE
sf::Keyboard::isKeyPressed together with ImGui::InputText

### ISSUE THREAD

**Issue by stawrocek** [eliasdaler/imgui-sfml#21]
Hi
If I enter text to ImGUI::InputText it still executes sf::Keyboard::isKeyPressed. I am sure that it is some focus related stuff, but I can't find it in imgui docs or Internet.

Example code:

```
#include "../include/imgui/imgui.h"
#include "../include/imgui/imgui-SFML.h"

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>
#include <SFML/Graphics/CircleShape.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(640, 480), "ImGui + SFML = <3");
    window.setFramerateLimit(60);
    ImGui::SFML::Init(window);

    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    sf::Clock deltaClock;
    char windowTitle[256]="Test";
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if (event.type == sf::Event::Closed) {
                window.close();
            }
        }

        if(sf::Keyboard::isKeyPressed(sf::Keyboard::A)){
            shape.move(0.1f, 0.f);
        }

        ImGui::SFML::Update(window, deltaClock.restart());

        //ImGui::ShowTestWindow();

        ImGui::Begin("Hello, world!");
        ImGui::Button("Look at this pretty button");
        ImGui::InputText("Window title", windowTitle, 255);
        ImGui::End();

        window.clear();
        window.draw(shape);
        ImGui::Render();
        window.display();
    }

    ImGui::SFML::Shutdown();
}
```

Now if I press 'A' then letters 'A' are being inserted into TextInput and simultaneously the circle is moving.
It would be great if `ImGui::SFML::ProcessEvent(event);` could return false/true depending on if it has 'used' this event to change gui state or if there is focused widget.

**Comment by stawrocek** [comment]
Moreover if I try to overcome this following way:
```
bool b = ImGui::InputText("Window title", windowTitle, 255);
std::cout << b << "\n";
```
then if I press a key then the output isn't constantly 1 (it changes randomly from 0 do 1). If i change `setFramerateLimit(60)` to `setFrameRateLimit(20)` then it begins working corectly (i.e. only 1 as output)

**Comment by eliasdaler** [comment]
ImGui doesn't modify your input in any way, it just reads it and applies to your widgets if they're in focus. Do the following check in your code so that if your widgets have focus, the game input won't be processed
```c++
if (!ImGui::GetIO().WantCaptureKeyboard) {
   ... // process game input
}
```

The second issue: the return value of InputText won't be true in every frame because of key repeat delay. It only returns "true" if there was new input. So, again, not an issue.
