### ISSUE TITLE
Custom fonts break tooltips

### ISSUE THREAD

**Issue by MarkSill** [eliasdaler/imgui-sfml#22]
I don't know if this is common to imgui on its own, but loading in a custom font breaks the rendering on tooltips, even when the font has not been pushed to the stack.

Font creation code:
```cpp
//mdFont and mdFontTexture are defined elsewhere.
//ICON_MIN_MD and ICON_MAX_MD are defined as part of https://github.com/juliettef/IconFontCppHeaders/blob/master/IconsMaterialDesign.h
io.Fonts->AddFontDefault();
static const ImWchar mdIconsRanges[] = {ICON_MIN_MD, ICON_MAX_MD, 0};
ImFontConfig mdIconsConfig;
mdIconsConfig.MergeMode = true;
mdIconsConfig.PixelSnapH = true;
mdFont = io.Fonts->AddFontFromFileTTF("MaterialIcons-Regular.ttf", 16.f, &mdIconsConfig, mdIconsRanges);
ImGui::SFML::createFontTexture(mdFontTexture);
ImGui::SFML::setFontTexture(mdFontTexture);
```

I'm pretty sure I'm doing everything as needed. The icons _do_ work, just tooltips appear to be rendering with garbage data.

**Comment by eliasdaler** [comment]
Hi. I didn't test custom fonts much, I'll take a look at it soon.

(Try using window.resetGlStates() before ImGui::Render()? If it works, I'll be amazed. :D)

**Comment by MarkSill** [comment]
Alright, well I fixed my problem. Even looking at the code, I can't figure out why, though. I'm passing a pointer to `ImGui::SFML::Init` that points to the font texture. This works regardless of the texture not being created yet. Anyway, it works, but I have no clue why.

I don't know whether I would call this is a bug or not, so I'll leave it to you to decide if you want to close this issue or not.

**Comment by MarkSill** [comment]
I have a correction. It appears that any texture passed to `ImGui::SFML::Init` works. I was passing in an unused texture by accident and it was still working. I changed it to the actual font texture, and it still works. This is smelling a bit more like a bug.

**Comment by MarkSill** [comment]
I can fix this in the library by removing `createFontTexture(*s_fontTexture);` after the texture is created in `ImGui::SFML::Init`.

Additionally, if I create the fonts before initializing ImGui (but don't call `ImGui::SFML::createFontTexture` and `ImGui::SFML::setFontTexture`), and then call `ImGui::SMFL::Init` without a texture pointer, then it works.

I'm pretty certain the issue arises from creating a font texture when no font information has been loaded. Of course, tooltips still work when I don't do this if I also don't create any fonts, so I don't know why that works.

**Comment by eliasdaler** [comment]
Fixed, [here's how to use custom fonts](https://github.com/eliasdaler/imgui-sfml#fonts-how-to).
