### ISSUE TITLE
`ImGuiKey_` has been renamed to `ImGuiKey` 

### ISSUE THREAD

**Issue by Bambo-Borris** [eliasdaler/imgui-sfml#220]
Whilst helping a user in the SFML Discord server I noticed that a change from a few days ago within imgui now means that it is not possible for a user to grab the master branch and use it with imgui-sfml. It causes build errors associated with the enum `ImGuiKey_` no longer being present.

Just thought I would leave an issue up in case someone runs into this. It is possible (and advised imo) to use the most recent stable release of imgui v1.88 instead.

**Comment by eliasdaler** [comment]
Fixed by #219
