### ISSUE TITLE
"ImGuiNavInput" instead of "ImGuiNavInput_"

### ISSUE THREAD

**Issue by differenceclouds** [eliasdaler/imgui-sfml#223]
I'm just starting a new project with xcode, so I'm not sure if I even have it set up correctly. However, the build fails unless I remove the trailing underscore from the two references to the "ImGuiNavInput_" enum on lines 131 and 1023 of imgui-SFML.cpp.

**Comment by eliasdaler** [comment]
Hello
Which version of ImGui-SFML are you using? Please see if current master version works for you.

**Comment by Dannode36** [comment]
I have the same problem using ImGui-SFML 2.5

**Comment by oprypin** [comment]
> Please see if current master version works for you.

**Comment by linuxing3** [comment]
> I'm just starting a new project with xcode, so I'm not sure if I even have it set up correctly. However, the build fails unless I remove the trailing underscore from the two references to the "ImGuiNavInput_" enum on lines 131 and 1023 of imgui-SFML.cpp.

I have the same problem using ImGui-SFML 2.5

**Comment by oprypin** [comment]
> Please see if current master version works for you.

**Comment by eliasdaler** [comment]
It should work. Closing for now.
