### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by buridan1999** [eliasdaler/imgui-sfml#226]
Get this error, while trying to link it was my project:

1>sfml-system-d.lib(sfml-system-d-2.dll) : error LNK2005: "public: __cdecl sf::String::~String(void)" (??1String@sf@@QEAA@XZ) alreay defined at ImGui-SFML.lib(imgui-SFML.obj)
1>D:\repos\rpg-pixelart\src\rpg-sfml\rpg-sfml\x64\Debug\rpg-sfml.exe : fatal error LNK1169:

**Comment by oprypin** [comment]
OK, I guess you should try to solve it then 🤷

**Comment by buridan1999** [comment]
It was my mistake, cause I try to link it with x86 version of SFML.
So i try to configur imgui-sfml cmake project again, and it can't find SFML if I give him x86 SFML.
But it work great with x64 version.

`"Start"
"RpgSfmlRoot: D:\repos\rpg-pixelart\src\rpg-sfml"
"SgmlDir: D:\repos\sfml\251_win32_vc19"
Подпапка или файл bin\ImGui-SFML уже существует.
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Warning at CMakeLists.txt:44 (find_package):
  Could not find a configuration file for package "SFML" that is compatible
  with requested version "2.5".

  The following configuration files were considered but not accepted:

    D:/repos/sfml/251_win32_vc19/lib/cmake/SFML/SFMLConfig.cmake, version: 2.5.1 (32bit)



CMake Error at CMakeLists.txt:47 (message):
  SFML 2 directory not found.  Set SFML_DIR to directory where SFML was built
  (or one which ccontains SFMLConfig.cmake)


-- Configuring incomplete, errors occurred!`

**Comment by eliasdaler** [comment]
This is more of an environment/IDE/build system problem than ImGui-SFML problem.
Try to get minimal SFML example to compile and then try to add ImGui-SFML to the mix.

Also try setting `IMGUI_SFML_FIND_SFML` to `OFF`

**Comment by buridan1999** [comment]
I pass -DSFML_DIR=%SFML-Dir% to cmake command, but it's can't find SFML...

**Comment by eliasdaler** [comment]
Are you able to compile basic SFML program without ImGui-SFML? 
This all looks like general CMake/IDE problems and I don't want to provide support about basics such as these. 

You can read [my article](https://eliasdaler.github.io/using-cmake/) about working with CMake and managing dependencies. It shows how to set up a project which uses SFML and ImGui-SFML.

**Comment by buridan1999** [comment]
@eliasdaler 
Yea, i fix it.
But problem is in .lib file naming, cause it's do not have -d suffix. Is it right?

**Comment by buridan1999** [comment]
It's here: https://github.com/eliasdaler/imgui-sfml/blob/master/CMakeLists.txt#L143
Why it setted only for (BUILD_SHARED_LIBS)?

**Comment by eliasdaler** [comment]
Described here: https://github.com/eliasdaler/imgui-sfml/pull/125

**Comment by buridan1999** [comment]
I use dynamic linking(

**Comment by buridan1999** [comment]
@eliasdaler I try to build it on ci\cd, and it's failed too... There are clear env
[0.txt](https://github.com/eliasdaler/imgui-sfml/files/9930587/0.txt)

**Comment by buridan1999** [comment]
Here such problem: https://github.com/eliasdaler/imgui-sfml/issues/108

**Comment by buridan1999** [comment]
fix it with -BUILD_SHARED_LIBS=ON
