### ISSUE TITLE
Minor Breaking Change in SFML2.6

### ISSUE THREAD

**Issue by Jim-Marsden** [eliasdaler/imgui-sfml#228]
First I would like to say that I will gladly do a PR for this, I just don't know how you'd want this done as far as branching.

sf::Keyboard::Quote and sf::Keyboard::Tilde were both changed recently in SFML 2.6. I know SFML is working to releasing SFML 2.6. 

In ImGui::keycodeToImGuiKey
sf::Keyboard::Quote -> sf::Keyboard::Apostrophe
sf::Keyboard::Tilde   -> sf::Keyboard::Grave

**Comment by oprypin** [comment]
It's not a **breaking** change in 2.6, only in 3.0. It is best to keep the existing code working until any release happens

https://github.com/SFML/SFML/blob/2.6.x/include/SFML/Window/Keyboard.hpp#L169
https://github.com/SFML/SFML/blob/8a307df494d1a8934384d8861cad3a1b9dbaaaba/include/SFML/Window/Keyboard.hpp#L169

**Comment by eXpl0it3r** [comment]
It's not breaking, but they are deprecated, so might make sense to update them. 🙂

**Comment by oprypin** [comment]
Sorry that my message is so decisive. I don't actually participate in this project. Mainly wanted to clarify.

**Comment by Jim-Marsden** [comment]
> Sorry that my message is so decisive. I don't actually participate in this project. Mainly wanted to clarify.

No, you were exactly correct. I was on the wrong branch when I thought it was removed. So quickly closed everything.

As it is deprecated in 2.6 it might be an issue for later, but as far as my issue goes, I was wrong.
