### ISSUE TITLE
Is there any way to prevent click events on ImGui from falling into SFML? 

### ISSUE THREAD

**Issue by DEAGS3000** [eliasdaler/imgui-sfml#24]
As the title, do ImGui or SFML have this function? Or I need to implement that by my self?

**Comment by MarkSill** [comment]
To my knowledge, there's no way of doing this automatically. You could potentially use `ImGui::IsAnyItemHovered()` or `ImGui::IsAnyItemActive()` (or perhaps a mixture of the two) to check.

**Comment by eliasdaler** [comment]
Yep, that's what I wanted to propose. To do so automatically would mean that I'd have to modify SFML's event queue which is not possible because of SFML's interface.

**Comment by Julzso23** [comment]
I recently solved this issue in my game by checking `ImGuiIO::WantCaptureMouse` and `ImGuiIO::WantCaptureKeyboard` before handling my mouse and keyboard events.

For example:
```
ImGuiIO& io = ImGui::GetIO();
switch (event.type)
{
    case sf::Event::MouseButtonReleased:
    {
        if (io.WantCaptureMouse) break;
        break;
    }
}
```

**Comment by eliasdaler** [comment]
More info:

From ImGui:

> You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
       - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
       - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
       Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
