### ISSUE TITLE
examples/main.cpp wrong include

### ISSUE THREAD

**Issue by xelfe** [eliasdaler/imgui-sfml#25]
there's a "#include "imgui_demo.h" at the beginning of examples/main.cpp but that file does not exist.

**Comment by MarkSill** [comment]
imgui_demo.h is part of the base imgui library. Is it in your include paths?

**Comment by xelfe** [comment]
The only file that begin by imgui_demo is imgui_demo.cpp.

$ find imgui/ -name "imgui_demo*"

imgui/imgui_demo.cpp
`

**Comment by MarkSill** [comment]
Ah, you're correct. My bad.

**Comment by xelfe** [comment]
so imgui_demo.cpp should be rename into imgui_demo.h ?

**Comment by MarkSill** [comment]
No, it should not. I haven't tested this, but I think the example should compile if you take out that include.

**Comment by eliasdaler** [comment]
You're right. I have no idea why that compiles on my and other systems , considering this is the first report about the issue. I'll remove the include, adding imgui_demo.cpp to your build process is enough.

Thanks!
