### ISSUE TITLE
Know if events was "consumed" by the GUI

### ISSUE THREAD

**Issue by Zenol** [eliasdaler/imgui-sfml#26]
Hello,

First, thanks for this awesome backend :)

I have a question. It seams it is not possible to know if an event has been used by ImGui, or if it didn't.
If the function ProcessEvent() could return a boolean telling if the event was "consumed" or not could be really useful (otherwise event will be handled both by the gui and the scene behind).

Unless this feature already exists?

Regards,

**Comment by eliasdaler** [comment]
Hi. You're welcome!

Take a look at #24, maybe that's what you want? Checking ImGui's state afterwards is what you're looking for, probably.

**Comment by Zenol** [comment]
Awesome, should do the job :)

Thanks for the quick reply!

**Comment by eliasdaler** [comment]
You're welcome. :)
