### ISSUE TITLE
getNativeHandle() const error in imgui-SFML.o?

### ISSUE THREAD

**Issue by MonkahTV** [eliasdaler/imgui-sfml#32]
Hi,

I've recently installed the imgui-SFML library you've created, and seem to be getting an error when attempting to include the header file provided.

`getNativeHandle() const - imgui-SFML.o`

is all the information my debugger is willing to provide.

Have you encountered this issue before? Would you happen to know what could possibly be causing it?

Thanks.

[Raspberry Pi / Raspibian Linux / GCC]

**Comment by eliasdaler** [comment]
Hi.

What SFML version are you using? Do minimal SFML applications work properly? What happens if you try to call `getNativeHandle` in a simple application? This may be SFML's implementation problem, as this function is OS specific.

**Comment by mikeagam-dev** [comment]
I am using the latest version of SFML-- downloaded the newest version as an attempt at a fix.
Minimal SFML applications work perfectly fine, can render textures, create shapes, and open windows just fine.

I'm not at work right now, so I'll have to get back to you on getNativeHandle()'s direct use sometime tomorrow. Though, if it's any help, I specifically recall that the errors mentioned this might be an issue with the Texture class.

Cheers!

**Comment by MonkahTV** [comment]
I am using the latest version of SFML-- downloaded the newest version as an attempt at a fix.
Minimal SFML applications work perfectly fine, can render textures, create shapes, and open windows just fine.

I'm not at work right now, so I'll have to get back to you on getNativeHandle()'s direct use sometime tomorrow. Though, if it's any help, I specifically recall that the errors mentioned this might be an issue with the Texture class.

Cheers!

**Comment by MonkahTV** [comment]
Hi.

This seems to be a problem with SFML, not with your library (which merely calls getNativeHandle()).

Apologies for the concern!

**Comment by eliasdaler** [comment]
Alright. Make sure to make issue in SFML repo as well. :)
