### ISSUE TITLE
Any chance of seeing sf::Font to ImFont conversion?

### ISSUE THREAD

**Issue by MonkahTV** [eliasdaler/imgui-sfml#34]
Would be nice to see in future builds. ;)

Cheers!

**Comment by eliasdaler** [comment]
Good idea! Especially seeing how there's this function in sf::Font:
```const Texture& getTexture(unsigned int characterSize) const;```
it should be easy to implement. Will see if it works soon. :)

**Comment by eliasdaler** [comment]
Hmmm... looks like it will be pretty hard. ImGui needs very specific atlas for custom font to work and SFML uses different format of them. But it's pretty easy to load your custom font:
```ImGui::GetIO().Fonts->AddFontFromFileTTF("Your_font.ttf", 8.f);```
This likely won't work without calling some additional functions, so I'll came up with a proper interface for changing the font and passing font filename and size to the changeFont function.

**Comment by MonkahTV** [comment]
Sounds good! Can't wait to see it!

**Comment by eliasdaler** [comment]
Done!
[How-to](https://github.com/eliasdaler/imgui-sfml#fonts-how-to)
