### ISSUE TITLE
gl 3d render not display but show imgui

### ISSUE THREAD

**Issue by Lightnet** [eliasdaler/imgui-sfml#40]
Tired a simple 3d cube rotate and it not displaying. Just showing the imgui. Need help.

**Comment by eliasdaler** [comment]
Hello.

Can you show me your full source code, please?

**Comment by Lightnet** [comment]
Sorry About that. Here my project build test. https://github.com/Lightnet/sfml_rpgen   main_sfml_rpgen.cpp main file for 3d render test.
