### ISSUE TITLE
event processing when drawing imgui form to a specified position

### ISSUE THREAD

**Issue by worldwar** [eliasdaler/imgui-sfml#41]
I'm facing a problem when integrating imgui to my sfml game.

I draw my gameplay area to window at {0, 0, 600, 600}, and I want to add a control panel to the right to the gameplay area, so the control panel rect in window is {600, 0, 100, 600}. To do that, I have to draw a imgui window to a sf::RenderTexture, and then draw this renderTexture to window at position {600, 0}. This is the code:

    ImGui::SFML::Update(window, _texture, deltaClock.restart());
    ImGui::Begin("Sample window"); // begin window
    if(ImGui::Button("Prepare", {60, 40})) {
        window.setTitle("xx");
    }
    ImGui::End();
    _texture.clear();
    ImGui::SFML::Render(_texture);
    sf::Sprite sprite(_texture.getTexture());
    sprite.setPosition(600, 0);
    window.draw(sprite);
    _texture.display();

However, after drawing the control panel to window, the control panel seems not knowing itself had been drawing to {600, 0}, and still accept mouse click events from position {0, 0}. I put a button in the control panel and the rect of the button is {650, 50, 50, 50}, but it can only react when I click at positions in rect {50, 50, 50, 50}. It looks like that only the view of the control panel has move to {600, 0}, the core of control panel is still at the original position {0, 0}.

So how can I fix it?

**Comment by eliasdaler** [comment]
Hello.

I see two possible solutions:

1) Draw window at {600, 0} directly like this:

```c++
ImGui::SetNextWindowPos(ImVec2(600, 0));
ImGui::Begin("Sample window"); // begin window
if(ImGui::Button("Prepare", {60, 40})) { // ImGui will use relative positions here, I think
    window.setTitle("xx");
}
...
```
Of course, you'll have to render it at {0, 0}.

2) Pass (your_real_mouse_position - { 600, 0 })  to ```ImGui::SFML::Update``` (see [this overload](https://github.com/eliasdaler/imgui-sfml/blob/master/imgui-SFML.cpp#L270)). This way, when you click at { 650, 50 }, you'll have ImGui thinking it was at { 50, 50 }.

I'm not sure that 2) will work properly for all cases, so I'd suggest going with 1).

**Comment by eliasdaler** [comment]
I think that should do it. Feel free to re-open if you still have questions about it. :)
