### ISSUE TITLE
Adding "ImGui::CreateContext()" because of future breakage in imgui

### ISSUE THREAD

**Issue by Epholys** [eliasdaler/imgui-sfml#44]
There will be a huge merge to master in imgui : https://twitter.com/ocornut/status/960649767691980800. A little breaking change is that `ImGui::CreateContext()` will need to be called once. Does imgui-sfml need this modification?
![screenshot from 2018-02-06 22-28-12](https://user-images.githubusercontent.com/7680863/35885201-68378b7a-0b8d-11e8-98f7-d733114ae269.png)

**Comment by eliasdaler** [comment]
Looks like ImGui::CreateContext() will be a thing in 1.60, and even though it's merged in ImGui's master, this version is still not released.
Once the 1.60 is released officially, I'll update ImGui-SFML. For now, I'll still support the latest release.

The only problem is that if someone just clones ImGui, ImGui-SFML won't work. What should I do? 🤔

**Comment by Epholys** [comment]
I think the last solution is a good one, with just a little note in the readme to make it clear :)

**Comment by eliasdaler** [comment]
Agreed! I'll do it soon then. :)

**Comment by aggsol** [comment]
How about creating tags corresponding the tags of imgui like current master gets tag 1.53 and the next release gets 1.60 which it will be comptaible with?!

**Comment by eliasdaler** [comment]
Oh no, entire month has passed! My definition of "soon" is close to Valve's...

Yes, this sounds good, but the problem with it is that I won't be able to patch bugs in 1.53 version if I find one when being on 1.60...

**Comment by Alia5** [comment]
I guess we could do patch branches and merge them with squashed commits in that case.
But it wouldn't really be as clean.

**Comment by SuperPrower** [comment]
I'm not sure if I'm in place in time, but I fixed all of my problems by replacing `ImGui::Shutdown` with `ImGui::DestroyContext` in imgui-SFML.cpp and running 'ImGui::CreateContext` in main.cpp before `ImGui::SFML::Init()`. Simple thing, but I think this may be useful for somebody.

**Comment by eliasdaler** [comment]
Done. [Use this version if you use v.1.53!](https://github.com/eliasdaler/imgui-sfml/releases/tag/v.1.0)

**Comment by nitro111** [comment]
anyád
