### ISSUE TITLE
ImGui::Shutdown accepts ImGuiContext* now

### ISSUE THREAD

**Issue by Falkgaard** [eliasdaler/imgui-sfml#46]
On line 319 of imgui-SFML.cpp there's:

`ImGui::Shutdown(); // need to specify namespace here, otherwise ImGui::SFML::Shutdown would be called`

However, in imgui.cpp on line 3601 there's:

`void ImGui::Shutdown(ImGuiContext* context)`

Due to the lack of a parameter in the call, I get the following errors during compilation:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)	E0135	namespace "ImGui" has no member "Shutdown"	RPGUI	c:\Users\Mithrala\Documents\Visual Studio 2017\Projects\RPGUI\RPGUI\imgui-SFML.cpp	319	
> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2039	'Shutdown': is not a member of 'ImGui'	RPGUI	c:\users\mithrala\documents\visual studio 2017\projects\rpgui\rpgui\imgui-sfml.cpp	319	

What should I edit it the argument to? I just got started with setting up the project, so I'm not very well acquainted with the code yet...

Thanks in advance for any help!
Regards,
-Falkgaard

**Comment by eliasdaler** [comment]
Hello

See #44 about this. It'll be fixed on this week. If you want to use ImGui now, use the latest [ImGui's release](https://github.com/ocornut/imgui/releases/tag/v1.53) for now.

**Comment by Falkgaard** [comment]
Hi,
I see! Thank you for the speedy reply. :)
Keep up the great work!
