### ISSUE TITLE
backspace erase the whole text instantly

### ISSUE THREAD

**Issue by fda-odoo** [eliasdaler/imgui-sfml#49]
Hello,

The backspace key is not detected as a letter, so it erase one letter at each frame. So if your application is fast enough, you erase the whole text without even seeing it...
Instead of it, souldn't the key be limited to some input per second?

Thank you

**Comment by eliasdaler** [comment]
Hello
Can you please make a short reproducible example, so I'm 100% sure I'm testing the same thing?

**Comment by fda-odoo** [comment]
I just did a minimal test that don't bug... I guess I failed to bind the right ascii code for the backspace key in my previous project. I'll investigate further on the project so, but it seems that it's my fault... I'll come back soon :)

**Comment by fda-odoo** [comment]
Ok it is effectively my fault as I tried to map QT event to sfml, but key code are differents, so it's a little tricky to get it works fine^^
Sorry for the false issue

**Comment by eliasdaler** [comment]
Haha, no problem. Glad that it works fine for you now.

**Comment by fda-odoo** [comment]
It doesn't work, but I know it is due to my code :) But fix it will take time :)
