### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#53]
This will be a TODO list for things to make once SFML has them in stable version:
- [x] System cursors (`sf::Cursor`)
- [x] Clipboard support (`sf::Clipboard`)
- [ ] Use scan codes instead of `sf::Keyboard` for input mapping
- [x] Better CMake integration: done in v2.0

_to be expanded..._

**Comment by eliasdaler** [comment]
sfml-2.5.0 branch is now available with cool new features!
I'll merge it into master in a few months to give people time to upgrade to it.

**Comment by codecat** [comment]
Ah, it just wasn't merged yet! I was about to open an issue for the system cursors.

In the meantime, I wrote some code for this outside of imgui-sfml:

```c++
		ImGuiMouseCursor currentCursor = ImGui::GetMouseCursor();
		if (currentCursor != prevCursor) {
			prevCursor = currentCursor;
			switch (currentCursor) {
			case ImGuiMouseCursor_Arrow: m_cursor.loadFromSystem(sf::Cursor::Arrow); break;
			case ImGuiMouseCursor_TextInput: m_cursor.loadFromSystem(sf::Cursor::Text); break;
			case ImGuiMouseCursor_ResizeAll: m_cursor.loadFromSystem(sf::Cursor::SizeAll); break;
			case ImGuiMouseCursor_ResizeNS: m_cursor.loadFromSystem(sf::Cursor::SizeVertical); break;
			case ImGuiMouseCursor_ResizeEW: m_cursor.loadFromSystem(sf::Cursor::SizeHorizontal); break;
			case ImGuiMouseCursor_ResizeNESW: m_cursor.loadFromSystem(sf::Cursor::SizeBottomLeftTopRight); break;
			case ImGuiMouseCursor_ResizeNWSE: m_cursor.loadFromSystem(sf::Cursor::SizeTopLeftBottomRight); break;
			case ImGuiMouseCursor_Hand: m_cursor.loadFromSystem(sf::Cursor::Hand); break;
			}
			m_window.setMouseCursor(m_cursor);
		}
``

**Comment by codecat** [comment]
Also, why not just use `SFML_VERSION_MAJOR` and `SFML_VERSION_MINOR` in preprocessing to check if the user is using SFML 2.5.0?

**Comment by eliasdaler** [comment]
Closing it, because scan codes won't come to SFML in near future and I'll create separate issues for needed improvement in the future.
