### ISSUE TITLE
Touch not found

### ISSUE THREAD

**Issue by gotocoffee1** [eliasdaler/imgui-sfml#54]
I think your last commit broke the [code](https://github.com/eliasdaler/imgui-sfml/commit/b0d5d16089d36654faefe18b58e4560a470ca032) since `Touch.hpp` isn't included on desktop builds anymore but e.g.: `sf::Touch::isDown(0)` is still [called](https://github.com/eliasdaler/imgui-sfml/blob/master/imgui-SFML.cpp#L315).

**Comment by eliasdaler** [comment]
Oops, my bad. Fixed, thanks. :)
