### ISSUE TITLE
Update calls sf::Window::setMouseCursorVisible

### ISSUE THREAD

**Issue by rachelnertia** [eliasdaler/imgui-sfml#56]
```cpp
window.setMouseCursorVisible(!ImGui::GetIO().MouseDrawCursor); // don't draw mouse cursor if ImGui draws it
```

In my game I want to hide the mouse at times (e.g. when the player is using the mouse to control the camera), so unhiding it every frame is a little bit unhelpful and can cause flickering. I'm not sure what a good solution is :/

**Comment by eliasdaler** [comment]
So, do you mean that you want game to capture the mouse and ImGui to temporarly ignore it?
Because you can disable mouse cursor in SFML by calling `window.setMouseCursorVisible(false);`

**Comment by rachelnertia** [comment]
I just want to hide the mouse cursor. Capturing it and making ImGui temporarily ignore it would be nice but isn't necessary as the mouse position is locked to the centre of the window anyway when mouse look is active.

I have to call `window.setMouseCursorVisible(false)` every frame because that line of code is making the cursor visible again. But even if I do this, sometimes there will be a delay between you setting it visible and me setting it invisible that is large enough for Windows to start showing the cursor again, so sometimes I get a flickering mouse cursor.

**Comment by eliasdaler** [comment]
I see, I've fixed it now. Now you only have to call `window.setMouseCursorVisible(false)` once! Indeed, it only makes sense to hide cursor if ImGui is drawing it, so if io.MouseDrawCursor is true, it will get hidden by default.

**Comment by rachelnertia** [comment]
Thanks!
