### ISSUE TITLE
ImGui::Image not working with sf::Sprite::SetTextureRect

### ISSUE THREAD

**Issue by rupee990** [eliasdaler/imgui-sfml#63]
Hello,

I'm Trying to make a preview screen for my Tile Select, I have a tilemap and im using SetTextureRect to only get one of the tiles from a tilemap, however when I use ImGui::Image, it shows the entire tilemap but very small.

This is When I have an id of -1 it will use the full texture:

![projectinfiltration_2018-08-16_12-09-44](https://user-images.githubusercontent.com/7471304/44220716-6d1d7180-a14d-11e8-8e9b-2d380f5eec4b.png)

then when I use an Id, it will recover the tile of that id, however the result is this:

![projectinfiltration_2018-08-16_12-10-04](https://user-images.githubusercontent.com/7471304/44220771-8cb49a00-a14d-11e8-8f8b-df05dacdde8f.png)

Here is the code:

```cpp
ImGui::Text("Preview:");
        sf::Sprite preview;
        sf::Texture* preview_texture = resourceManager->GetTexture(tx_selected);
        preview.setTexture(*preview_texture);

        ImGui::SliderInt("Tile Id", &tx_id, -1, preview.getTexture()->getSize().x / TILE_SIZE * preview.getTexture()->getSize().y / TILE_SIZE);

        if (tx_id != -1)
        {
            //Get Texture Uvs
            int tu = tx_id % (preview.getTexture()->getSize().x / TILE_SIZE);
            int tv = tx_id / (preview.getTexture()->getSize().x / TILE_SIZE);

            //preview.setTextureRect(sf::IntRect(sf::Vector2i(tu * TILE_SIZE, tv * TILE_SIZE), sf::Vector2i(TILE_SIZE, TILE_SIZE)));
            preview.setTextureRect(sf::IntRect(0,0,16,16));
        }

        ImGui::Image(preview); 
```

Sorry for messy code.

**Comment by rupee990** [comment]
instead of using ImGui::Image, I got the drawList and and added an image, was a bit tricky to make it work but now it works fine :) For anyone facing a similar issue.

![2018-08-16_14-28-55](https://user-images.githubusercontent.com/7471304/44227481-be832c00-a160-11e8-89c0-5b11fa8f9c3e.gif)

**Comment by eliasdaler** [comment]
Hello. Can you please check if [this PR](https://github.com/eliasdaler/imgui-sfml/pull/62) fixes your problem? Seems similar.

**Comment by eliasdaler** [comment]
Merged. I'll close the issue.

Cheers.
