### ISSUE TITLE
SFML 2.5.0?

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#65]
Right now, I've managed to get SFML to get ImGui-SFML to work with SFML 2.3 and higher, check this branch out: https://github.com/eliasdaler/imgui-sfml/tree/sfml-2.5.0

As SFML and ImGui grow, I find it harder to support everything. I need to add #ifdefs to support older SFML versions, but the questions is - is it worth it? How long should we support older SFML versions?

And it's not only about features, but CMake support too. SFML 2.5.0 was a huge step forward for SFML's CMake, which will makes integrating it with ImGui-SFML much easier, so if it was in my power, I'd drop SFML < 2.5.0 now. Supporting pre-SFML-2.5.0. CMake integrations is close to having two different CMake's for ImGui-SFML - not cool.

So, what are your thoughts?

**Comment by eXpl0it3r** [comment]
I don't see a reason for people to stick with an old version of SFML, as such ImGui-SFML shouldn't have to stick to an old version. If someone really wants to use an old SFML version, there's always the option to either stick with an old version of ImGui-SFML or just do some more fiddling to get it working.

**Comment by FinchZ** [comment]
I want to use IMGUI with the lasted version of SFML.
then I find a little build errors.
I think it may be the problem of the version of the codes.
so I try to write a library by myself...

**Comment by eliasdaler** [comment]
Dropped SFML < 2.5.0 support with ImGui-SFML v2.0. Closing.
