### ISSUE TITLE
C++11?

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#7]
I tried to avoid using C++11 because ImGui and SFML don't use it and I didn't want to introduce new dependencies.
But I've noticed lately that I used `nullptr` and there were no complaints about that. So, what if I moderately use C++11 from now on? Here's some stuff I want to use (all of it is supported in VS 2010+ and in old GCC and Clang versions):
- `auto`
- `nullptr`
- `unique_ptr`

**Comment by eXpl0it3r** [comment]
Yes. Plus don't shy away from dropping VS 2010 support. :wink:

**Comment by floooh** [comment]
VS2013 (not sure about VS2015) has incomplete support for const_expr, initializer lists and std::chrono::high_resolution_timer only has millisecond accuracy (not sure if they fixed that in one of the recent updates). Other then that I haven't come across major C++11 showstoppers across platforms (gcc 4.8, clang 3.x, VS2013+2015).

**Comment by EliasD** [comment]
A lot more people are willing to accept C++11 in this binding which is very cool!
I don't want to lose some of people who can't use C++11, though. Right now not using C++11 doesn't hurt quality of code or end user interface. A little of my pain which will go unnoticed! :D

If I really need C++11 only stuff (like lambdas or something like that) and using old features would hurt the perfomance/readability/end user interface then I'll use it and at the same time I'll try to make it optional. :)

**Comment by susnux** [comment]
I think also the next major sfml release will make use of c++11 (sfml 3.x)

**Comment by eliasdaler** [comment]
@susnux yeah, this will be so neat

**Comment by RUSshy** [comment]
c++ 17 ? be modern :p

**Comment by DNKpp** [comment]
Any new thoughts about that topic?

**Comment by eliasdaler** [comment]
Once SFML is going to have a stable release with C++17 in it, I might use C++17 in ImGui-SFML too.

**Comment by DNKpp** [comment]
Hm, the (quite old) topic was about c++11. The readme states that you still target 03. Is that still valid? If so, is there a chance that you at least start targeting 11 (or even 14)?

**Comment by eliasdaler** [comment]
Yes, ImGui-SFML still works on C++03. C++11 seems a bit old and if we go "modern C++" it doesn't make sense to stick with version that's over 10 years old.

**Comment by eliasdaler** [comment]
Reopening, since [this](https://github.com/ocornut/imgui/commit/f5d54f4ea9d1b4685914c09de0e0b7adf1830569) is a thing now.

Please note that for now only C++11 (not C++14,17, etc.) will be used.

**Comment by eliasdaler** [comment]
Actually, I'll create a new issue about this. :)
