### ISSUE TITLE
Update to demo code needed

### ISSUE THREAD

**Issue by scottfurry** [eliasdaler/imgui-sfml#71]
I had followed example code shown on [blog page](https://eliasdaler.github.io/using-imgui-with-sfml-pt1/) and was receiving multiple linking errors indicating imgui-SFML constructs could not be found. Buried in the comments was a suggestion from a user from a month ago...

> Just came here to say that you should also add imgui-widgets.cpp to your file. Otherwise you will stuck with LNK2019 errors.

I think this may also be an upstream problem with incomplete instructions.

What worked for me...
Add to building instructions the need to include "ingui_widgets.cpp". All linking problems disappear after this inclusion.

**Comment by scottfurry** [comment]
Also note... blog post referenced above uses
`#include "imgui-sfml.h"`

Latest example code uses
`#include "imgui-SFML.h"`

**Comment by eliasdaler** [comment]
Thanks a lot!
I knew about imgui-widgets.cpp, but was a bit lazy to fix it. Now it's done, check it out](https://eliasdaler.github.io/using-imgui-with-sfml-pt1/#setting-up)
