### ISSUE TITLE
Which branch to use for SFML 2.5.x release and dear-imgui v1.69 release

### ISSUE THREAD

**Issue by yxbh** [eliasdaler/imgui-sfml#74]
Hi,

Not sure if this is the bad place to ask so my apologies if it isn't. 

I am trying to figure which branch is the best one to use for the current releases of SFML and dear-imgui. I had a look at the branch graph and it looks like all the different branches (develop, SFML 2.5.0, etc) are ahead and behind by different commits.

Thank you for your help :)

**Comment by eliasdaler** [comment]
Hello. This is a good place to ask (though feel free to e-mail/tweet at me for quick questions)

Try out **develop** branch. It's almost ready to be merged into master, I'm just waiting for more people to test it to do so.

**Comment by yxbh** [comment]
Thanks Elias, I've been a little busy the last few days but I will give it a go and report back when I have some time for my project this weekend :)

**Comment by yxbh** [comment]
Apologies for the very late update. I've finally managed to integrate imgui v1.69 and imgui-sfml *develop* branch into my project with SFML2.5.1.

I've got the [sample app console](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp) running inside my own project :)

So far so good 👍

**Comment by eliasdaler** [comment]
Now you can use stable 2.0 release. Closing.
