### ISSUE TITLE
Mouse wheel delta

### ISSUE THREAD

**Issue by immortalx74** [eliasdaler/imgui-sfml#83]
There seems to be a mouse wheel delta issue with specific mice. I described the problem in imgui's issues here: [url](https://github.com/ocornut/imgui/issues/2581)

**Comment by eliasdaler** [comment]
Please write a test program which catches `sf::Event::MouseWheelMoved` and writes `event.mouseWheel.delta` to console. What values do you get when you rotate the mouse?

**Comment by eliasdaler** [comment]
Ah, I see that it has been deprecated in SFML 2.5.
Try out this event: `sf::Event::MouseWheelScrollEvent` and see what values `event.mouseWheelScroll.delta` outputs.

**Comment by immortalx74** [comment]
Thanks for looking in to this. When I move the wheel slowly (in which case it actually doesn't scroll at all) I get this output:
`wheel type: vertical
wheel movement: 0.75
mouse x: 464
mouse y: 265
wheel type: vertical
wheel movement: -0.5
mouse x: 464
mouse y: 265
wheel type: vertical
wheel movement: -0.25
mouse x: 464
mouse y: 265
wheel type: vertical
wheel movement: -0.25
mouse x: 464
mouse y: 265
wheel type: vertical
wheel movement: -0.25
mouse x: 464
mouse y: 265
wheel type: vertical
wheel movement: -0.25
mouse x: 464
mouse y: 265`

And when I move it fast (which is when it actually scrolls) I get this:
`wheel type: vertical
wheel movement: -1
mouse x: 379
mouse y: 321
wheel type: vertical
wheel movement: -1
mouse x: 379
mouse y: 321
wheel type: vertical
wheel movement: -1.5
mouse x: 379
mouse y: 321
wheel type: vertical
wheel movement: -1.75
mouse x: 378
mouse y: 320
wheel type: vertical
wheel movement: -1
mouse x: 374
mouse y: 311
wheel type: vertical
wheel movement: -1
mouse x: 370
mouse y: 302
wheel type: vertical
wheel movement: -0.75
mouse x: 368
mouse y: 299
wheel type: vertical
wheel movement: -1
mouse x: 368
mouse y: 296`

**Comment by eliasdaler** [comment]
Okay.
Can you try out this branch, please? 
https://github.com/eliasdaler/imgui-sfml/tree/mouse-scroll-fix

**Comment by immortalx74** [comment]
That works perfectly! Thank you very much for taking the time to do it!

**Comment by eliasdaler** [comment]
Nice. I'll merge it into master and release 2.0.2 later today. :)
