### ISSUE TITLE
vcpkg support

### ISSUE THREAD

**Issue by eliasdaler** [eliasdaler/imgui-sfml#96]
Some people suggested that imgui-sfml should be on vcpkg, and I think it's a good idea, so some day that should be done.

**Comment by kiwixz** [comment]
Hi, I opened a PR over there: microsoft/vcpkg#8004

**Comment by eliasdaler** [comment]
https://github.com/microsoft/vcpkg/pull/7429 has been merged into vcpkg
If someone has issues with it, please report it to vcpkg, I won't be supporting vcpkg package. If something is not possible to do because of how imgui-sfml does things, please open an issue here.
